### ISSUE TITLE
Produce server error

### ISSUE THREAD

**Issue by vladkras** [spiral/php-grpc#1]
Is there any way to send custom errors like js does with Error object?
Or are you waiting for https://github.com/grpc/grpc/issues/4546?

**Comment by wolfy-j** [comment]
You can use custom exception messages already: https://github.com/spiral/php-grpc/blob/master/tests/src/Test/TestService.php#L22

Maybe you can you give me a specific example? We can support any error messages supported by golang grpc implementation.

**Comment by wolfy-j** [comment]
@vladkras let me know if you have any particular requirements for this feature, I'm closing this ticket till then.
