### ISSUE TITLE
Metadata from server

### ISSUE THREAD

**Issue by antham** [spiral/php-grpc#14]
Hi, I can't figure out how to send metadatas from server, do you have any clue about that ?

**Comment by wolfy-j** [comment]
Hi,

sorry about not mentioning about this part in documentation (still waiting to focus on it more).

You can send metadata using the default context and "google.golang.org/grpc/metadata":
https://github.com/spiral/php-grpc/blob/master/proxy_test.go#L108

You can receive it using Context:
https://github.com/spiral/php-grpc/blob/master/tests/GRPC/ContextTest.php

**Comment by antham** [comment]
Yes but from the php server you can't do this ?

**Comment by wolfy-j** [comment]
You should be able to. Check the official client documentation, I can also see metadata in here:
https://github.com/grpc/grpc/blob/master/src/php/lib/Grpc/UnaryCall.php

**Comment by antham** [comment]
Ok thanks for your answer I will check that

**Comment by gigi** [comment]
Hi!
@antham do You have any working example? Can't figure out how to work with the ContextInterface and send metadata from server to client properly

**Comment by wolfgang-braun** [comment]
Hi @antham @gigi the requested functionality is now implemented: https://github.com/spiral/php-grpc/blob/master/tests/src/Test/TestService.php#L64

`$ctx->getValue(GRPC\ResponseHeaders::class)->set('foo', 'bar');`

**Comment by antham** [comment]
Thanks for this information @wolfgang-braun

**Comment by wolfy-j** [comment]
More docs are here: https://spiral.dev/docs/grpc-client
