### ISSUE TITLE
support specification of additional ServerOptions such as MaxRecvMsgSize

### ISSUE THREAD

**Issue by chaseajen** [spiral/php-grpc#20]
it looks like the only supported ServerOptions are related to TLS. the ability to specify additional options — in my case, particularly `MaxRecvMsgSize` — would be quite useful.

**Comment by wolfy-j** [comment]
You can actually add an option to the service, the values just simply not exposed through the config cos there is a lot of different values. I would accept PR if anyone wants to add more options.

**Comment by 48d90782** [comment]
Will be resolved with #43

**Comment by 48d90782** [comment]
Done by #47

**Comment by aleksandr-f** [comment]
Hi, it looks like, that MaxRecvMsgSize option does not work. We use:
```
github.com/spiral/php-grpc v1.5.0
github.com/spiral/roadrunner v1.8.3
```
In .rr.yaml (settings by default) we have:
```
# max send limit (MB)
MaxSendMsgSize: 50
```
But when we send a gRPC request, which is more than 4194304 bytes, then we have an error:

> 8 RESOURCE_EXHAUSTED: grpc: received message larger than max (5294178 vs. 4194304)

We found, that this error comes from https://github.com/grpc/grpc-go/blob/master/rpc_util.go.

Do you have the same issues or did you even try to send something, which is more than 4 MB?

**Comment by aleksandr-f** [comment]
Hi, it looks like, that MaxRecvMsgSize option does not work. We use:
```
github.com/spiral/php-grpc v1.5.0
github.com/spiral/roadrunner v1.8.3
```
In .rr.yaml (settings by default) we have:
```
# max receive limit (MB)
MaxRecvMsgSize: 50
```
But when we send a gRPC request, which is more than 4194304 bytes, then we have an error:

> 8 RESOURCE_EXHAUSTED: grpc: received message larger than max (5294178 vs. 4194304)

We found, that this error comes from https://github.com/grpc/grpc-go/blob/master/rpc_util.go.

Do you have the same issues or did you even try to send something, which is more than 4 MB?
