### ISSUE TITLE
Rich error model

### ISSUE THREAD

**Issue by evsign** [spiral/php-grpc#21]
Hi, thanks for the project!!
Is there are possible to use rich error model?
https://www.grpc.io/docs/guides/error/
https://cloud.google.com/apis/design/errors#error_model

**Comment by wolfy-j** [comment]
Yes, take a look at these exceptions: https://github.com/spiral/php-grpc/tree/master/src/Exception

**Comment by evsign** [comment]
Ammm, if i clealy understand its a basic grpc error model, which can produce only code and error message. In rich error model you can pass in status additionals errors details, for example stack trace or validation errors in special `details` field.

```
package google.rpc;

message Status {
  // A simple error code that can be easily handled by the client. The
  // actual error code is defined by `google.rpc.Code`.
  int32 code = 1;

  // A developer-facing human-readable error message in English. It should
  // both explain the error and offer an actionable resolution to it.
  string message = 2;

  // Additional error information that the client code can use to handle
  // the error, such as retry delay or a help link.
  repeated google.protobuf.Any details = 3;
}
```

**Comment by wolfy-j** [comment]
Hmm, I see. Custom codes and messages are already being passed, we have to add support for details only.
