### ISSUE TITLE
Way to define Interceptors or Middlewares for OAuth?

### ISSUE THREAD

**Issue by lrembacz** [spiral/php-grpc#24]
Hi,
Is there a way or is planned to define some kind of Interceptors or Middlewares for this gRpc server?

Something like in this post would be great I guess:

https://texlution.com/post/oauth-and-grpc-go/

**Comment by wolfy-j** [comment]
Yes, you can define Interceptor by implementing InvokerInterface:
https://github.com/spiral/php-grpc/blob/master/src/InvokerInterface.php

And pass it the server: https://github.com/spiral/php-grpc/blob/master/src/Server.php#L33

You can wrap default Invoker to implement needed functionality.

**Comment by lrembacz** [comment]
Yes, I can see that. 
Thank you for your answer and this work.
