### ISSUE TITLE
Does php-grpc support retries?

### ISSUE THREAD

**Issue by paquettg** [spiral/php-grpc#26]
I could not find any documentation on how to leverage the rpc retry functionality.

Is this supported?

Thank you.

**Comment by wolfy-j** [comment]
Hi,

sorry for missing this ticket earlier. This is server library, as far as you client support retries you can use them.

**Comment by wolfy-j** [comment]
You can read how to write clients here https://spiral.dev/docs/grpc-client

Retry is **not** part of default GRPC package but you can easily write it by yourself.
