### ISSUE TITLE
Support sending HTTP headers

### ISSUE THREAD

**Issue by wolfgang-braun** [spiral/php-grpc#28]
Hi

I tried to find out how to add custom HTTP headers to the php-grpc server response.

Despite [this](https://github.com/spiral/php-grpc/issues/14#issuecomment-483984846) tt seems that this is not possible right now?

In golang I'd set response-headers like that:
`grpc.SendHeader(ctx, metadata.New(map[string]string{"foo": "bar"}))`

I tried to find the place where the headers/metadata should be sent.
Is this the place: https://github.com/spiral/php-grpc/blob/master/proxy.go#L119 ?

If you tell me how you want the feature to be implemented I can provide a PR.

thanks

**Comment by wolfy-j** [comment]
Your PR will be appreciated. We will have to include the ability to set the response context and pass it to the server.

**Comment by wolfgang-braun** [comment]
@wolfy-j Okay, this would be my approach: https://github.com/spiral/php-grpc/pull/30
Do you mean it to be done like that, or do you prefer another way of implementing the feature?
