### ISSUE TITLE
add external services how to get roadruner.server?

### ISSUE THREAD

**Issue by pyeno** [spiral/php-grpc#31]
Excuse me, I need to add `external services` when developing php-grpc server, and initiate a request for php worker in` external services`. When reading the go source code, I found:

// external services
for _, r: = range svc.services {
r (server)
}
Didn't pass roadruner.server as a parameter?

In addition,  service.Server () is in lock, and a direct call will cause a deadlock.

**Comment by wolfy-j** [comment]
Hi, use https://github.com/spiral/php-grpc/blob/master/service.go#L45

It will register a new service.

**Comment by pyeno** [comment]
I want to add a grpc service and operate rr in the grpc service.
https://github.com/spiral/php-grpc/blob/master/service.go#L45
How does the grpc service added in this function get https://github.com/spiral/php-grpc/blob/master/service.go#L29?

**Comment by pyeno** [comment]
https://github.com/spiral/php-grpc/blob/master/service.go#L186 This line of code does not pass a parameter rr * roadrunner.Server

**Comment by pyeno** [comment]
I want to add a custom grpc service and operate rr in the grpc service.
Use this function:
https://github.com/spiral/php-grpc/blob/master/service.go#L45
How to get https://github.com/spiral/php-grpc/blob/master/service.go#L29 in the custom grpc service?

**Comment by wolfy-j** [comment]
Hi,

you have to create a new RR service and register it's in GRPC (request it as a dependency).

https://roadrunner.dev/docs/beep-beep-service

This is the example: https://github.com/spiral/php-grpc/blob/master/service_test.go#L446

Let me know if this is what you are looking for.

P.S. We will try to write more about GRPC in our documentation early next year.

**Comment by pyeno** [comment]
thx, i get it. its work.
