### ISSUE TITLE
[FEATURE REQUEST] Enabling Max Connection Age

### ISSUE THREAD

**Issue by Bibob7** [spiral/php-grpc#43]
I want to set a maximum age for connections on service site.

Is it possible to set something like `grpc.max_connection_age_ms` or in general configs from here:

https://grpc.github.io/grpc/core/group__grpc__arg__keys.html#gabd3a16f46ad2cb5f06064bb607df7b5b

**Comment by wolfy-j** [comment]
@48d90782 can we check later if Golang API exposes this?

**Comment by 48d90782** [comment]
@Bibob7 @wolfy-j  Yep, this is C++ API as far as I know and this is very easy to expose this API via the config (.rr.yaml) in golang. We will release this according to the RR release cycle (16 of June). 
FYI in golang default value for the max_connection_age is 30 seconds.
