### ISSUE TITLE
Support setting grpc headers from config, as supported for http in RoadRunner

### ISSUE THREAD

**Issue by frickenate** [spiral/php-grpc#44]
I know the `php-grpc` project fairly recently added support for setting grpc response headers/context/metadata from the code of php workers. However, it would be useful to be able to set globally-applicable headers from the yaml config file, as is supported for http in the base RoadRunner project [according to the docs](https://roadrunner.dev/docs/http-headers). Obviously the CORS section does not apply, but being able to set maps for `headers.request` and `headers.response` in the config file is desirable for our project.

The version of the base `spiral/roadrunner` in `go.mod` _could have supported_ setting headers from config since `php-grpc` version `1.0.8`, when `spiral/roadrunner` was bumped from version `1.4.2` to `1.4.8` (headers were added to the roadrunner dependency in version `1.4.4`). However, no code was added to the `php-grpc` project to read the `headers` section of the config to affect grpc requests and responses.

I can't think of a reason as to why `php-grpc` should not allow setting headers for all grpc requests and responses from config. Support for this would better align this project with the base RoadRunner project and its documentation.

**Comment by wolfy-j** [comment]
Technically it's different dispatching methods. We are open to accepting PR for header support in it. If not - we will handle it after preparing the foundation for 2.0 release of RR.
