### ISSUE TITLE
Plans for the project moving forward

### ISSUE THREAD

**Issue by Reasno** [spiral/php-grpc#5]
We are in dire need for a grpc server in php for quite a while. This projects filled that gap. I would love to see the project grow and make contribution where needed. I hope it is not abandoned.

**Comment by wolfy-j** [comment]
All of the projects in spiral account of github are maintained by SpiralScout company. This project is not abandoned but we have more than 40 open source projects and internal work, please stay tight or help us to find someone who can solve this issue. We can always provide guidance at our Discord server (link is in RR repo).

**Comment by wolfy-j** [comment]
Also, please note this library be a part of roadrunner-ce in combination with HTTP and Queue servers and other features. This app is significant part of our infrastructure.

**Comment by wolfy-j** [comment]
I guess i can close it now :)
