### ISSUE TITLE
Server error details

### ISSUE THREAD

**Issue by aldump** [spiral/php-grpc#50]
https://github.com/spiral/php-grpc/blob/33f8cc2c65010bd98870be7cb581f160915767be/src/Server.php#L88-L90

I think server should not show to clients its guts.
Consider just sending error text, instead full stack trace.

It also leads to error "received trailing metadata size exceeds limit", since client could be not prepared with increased "max_metadata_size" for handling really big stack trace. 

So I think it should be limited with only error message

I can do pull request if, you wish

**Comment by wolfy-j** [comment]
Maybe adding debug on/off option.

**Comment by aldump** [comment]
would be even better

**Comment by wolfy-j** [comment]
Would you mind adding PR for it?

**Comment by aldump** [comment]
Sure, no problem

**Comment by aldump** [comment]
[Pull request](https://github.com/spiral/php-grpc/pull/51)

I don't what to do with increased complexity, but I hope It's not a problem. But anyway all comments are welcome

**Comment by wolfy-j** [comment]
This is good! Thank you for the code and for the test.
