### ISSUE TITLE
How to Implement a Client Authentication?

### ISSUE THREAD

**Issue by khal3d** [spiral/php-grpc#57]
Hi,

I'm looking for a way to implement client authentication before starting communicating with my gRPC server (PHP).

For example, the client supposes to send an `app-id` and `secret-key`, and the server validates these tokens before responding.

**Comment by wolfy-j** [comment]
Check the metadata https://spiral.dev/docs/grpc-service#metadata

**Comment by khal3d** [comment]
Yeah, I have checked the metadata & using the gRPC headers, but is this the best way to implement this? 

I don't like the idea of doing an auth check before every single method in my service. 
I'm looking for something that can be applied to all the calls...

**Comment by wolfy-j** [comment]
Ah, check the invoker abstraction - https://github.com/spiral/php-grpc/blob/master/src/InvokerInterface.php It has access to the context, you can pass it to the GRPCServer.
