### ISSUE TITLE
spiral/php-grpc incompatible with spiral/roadrunner-laravel on PHP 8

### ISSUE THREAD

**Issue by awarrenlove** [spiral/php-grpc#63]
I see PHP 8 support was added to this package recently. However, the `"spiral/roadrunner": "^1.8"` dependency appears to lock us to PHP 7.2, so I am unable to install this package in a PHP 8.0 project.

**Comment by wolfy-j** [comment]
Weird, 1.9 supports PHP8, did you lock 1.8?

**Comment by awarrenlove** [comment]
Oops, I read the composer output incorrectly. Let me edit the title.

It's actually `spiral/goridge:^3.0` that is incompatible, required through `spiral/roadrunner-worker:^2.0` which is required through `spiral/roadrunner-laravel:^4.0`. I will see if I can downgrade that package.

**Comment by wolfy-j** [comment]
Well... in that case you have to wait a bit, we do not support GRPC in RR2 _yet_. But it's in our pipeline to get it done soon enough. @48d90782

**Comment by awarrenlove** [comment]
I see. Thank you.

It also looks like PHP 8 with GRPC still isn't supported, unless I'm interpreting this dependency chain incorrectly. It looks like the most recent version of spiral/roadrunner-laravel that references RR1 is v3.7.0, but that requires RR v1.8 which does not allow PHP 8.
