### ISSUE TITLE
Pre-built binaries missing for v1.4.2 and v1.5.0?

### ISSUE THREAD

**Issue by rochacon** [spiral/php-grpc#64]
It seems like the pre-built binaries for [v1.4.2](https://github.com/spiral/php-grpc/releases/tag/v1.4.2) and [v1.5.0](https://github.com/spiral/php-grpc/releases/tag/v1.5.0) are missing from the releases page, did it move somewhere else?

**Comment by 48d90782** [comment]
@rochacon yeah, give me a second 😄

**Comment by 48d90782** [comment]
@rochacon Here you are: https://github.com/spiral/php-grpc/releases/tag/v1.5.0

**Comment by 48d90782** [comment]
Feel free to close the ticket, if everything is fine)

**Comment by rochacon** [comment]
Thank you @48d90782 !
