### ISSUE TITLE
[FEATURE] PSR-2 Compatible Method Names

### ISSUE THREAD

**Issue by bgultekin** [spiral/php-grpc#67]
[Protocol Buffer Styling Guide](https://developers.google.com/protocol-buffers/docs/style) suggests using camel case (with an initial capital) method names in service definitions. But when we do that, it's making the service file incompatible with PSR-2 (and PSR-12) because it generates the method names same as in the proto file.

Shouldn't the plugin generate PSR-2 (or maybe optional) compatible files no matter what is given? It looks like, that's how the java plugin works.

Thanks for the great tool BTW! It's very helpful.

**Comment by wolfy-j** [comment]
I'm open to that, but it will require patching the proto file compiler. We can conder something like that in future releases. Any PR will be appreciated.
