### ISSUE TITLE
Plugin killed by signal 11.

### ISSUE THREAD

**Issue by pandelix** [spiral/php-grpc#69]
When I run this:
`protoc ./protos/example.proto --php_out=app/Libs/Grpc --grpc_out=app/Libs/Grpc --plugin=protoc-gen-grpc=/usr/local/bin/protoc-gen-php-grpc`

It throws the following error:
`--grpc_out: protoc-gen-grpc: Plugin killed by signal 11.`

And it's fine when I use "grpc_php_plugin"

Please help me to solve it.

**Comment by wolfy-j** [comment]
Does it work with sample protos from the documentation?

https://spiral.dev/docs/grpc-service

Can you make sure to follow all the steps on the installation?

**Comment by pandelix** [comment]
> Does it work with sample protos from the documentation?
> 
> https://spiral.dev/docs/grpc-service
> 
> Can you make sure to follow all the steps on the installation?

I thought I installed the "protoc-gen-php-grpc", but I was wrong
