### ISSUE TITLE
PHP-GRPC client

### ISSUE THREAD

**Issue by briand-icabbi** [spiral/php-grpc#7]
Hi,

This is an interesting project, and I'd like to explore developing a series of services that use GRPC. I didn't see this answered elsewhere, but was wondering about PHP based GRPC clients? 

The example has a PHP GRPC server, but a NodeJS client. If a PHP server needs to call another service, should I generate a PHP client separately using the https://github.com/grpc/grpc extension?

Thanks,

Brian

**Comment by wolfy-j** [comment]
This is correct. This is only the server part of the implementation, you can use default GRPC library to generate clients.
