### ISSUE TITLE
Use Roadrunner 2

### ISSUE THREAD

**Issue by Bibob7** [spiral/php-grpc#73]
Are there any plans to update to Roadrunner version 2.* soon?

**Comment by wolfy-j** [comment]
Yes, ETA 2-3 months.

**Comment by rustatian** [comment]
@Bibob7 Working on it: https://github.com/spiral/roadrunner/pull/783

**Comment by Bibob7** [comment]
Since the issue is closed. Is there already a way to use roadrunner 2 with grpc. If not, when do you plan to release it?

**Comment by rustatian** [comment]
Hey @Bibob7 . Yep, feel free to try the first alpha release: https://github.com/spiral/roadrunner-binary/releases/tag/v2.5.0-alpha.1
as well with new GRPC PHP client library https://github.com/spiral/roadrunner-grpc

**Comment by revilon1991** [comment]
@rustatian Do you mean that this repo will be abandoned?
So, we have to use another repo https://github.com/spiral/roadrunner-grpc

**Comment by rustatian** [comment]
@revilon1991 No, this repo will be supported for security or bug fixes. 
With `Spiral` v2.9 (not released yet) and RR2 you should use the new PHP GRPC library https://github.com/spiral/roadrunner-grpc.
