### ISSUE TITLE
`protoc-gen-php-grpc` plugin support

### ISSUE THREAD

**Issue by hotrush** [spiral/php-grpc#77]
I can see that the code of `protoc-gen-php-grpc` plugin moved to the plugins repo https://github.com/spiral/roadrunner-plugins/tree/master/grpc/protoc_plugins/protoc-gen-php-grpc.

That arises some questions:

- which version should we use, which one you are going to maintain?
- if from plugins repo - do you plan to publish binaries like for this repo?

**Comment by rustatian** [comment]
Hey @hotrush. This repository was deprecated and will receive only urgent bug or security fixes.
Regarding your questions:
> which version should we use, which one you are going to maintain?

https://github.com/spiral/roadrunner-plugins/tree/master/grpc/protoc_plugins/protoc-gen-php-grpc

> if from plugins repo - do you plan to publish binaries like for this repo?

Yes, we will publish `protoc-gen-php-grpc` binaries in the https://github.com/spiral/roadrunner-binary repository shortly.

**Comment by rustatian** [comment]
@hotrush https://github.com/spiral/roadrunner-binary repo now contains `protoc-gen-php-grpc` binaries.
